#!/usr/bin/env bash
# transfers a file from our client to a server
# Accepts four parameters:
#+    1. The path to the file to be transferred.
#+    2. The IP of the server to transfer the file to.
#+    3. The username that scp connects with.
#+    4. The path to the SSH private key that scp uses.
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit
fi
path="$1"
ip="$2"
user="$3"
pass="$4"
scp -o StrictHostKeyChecking=no -i "$pass" "$path" "$user@$ip":~
