#!/usr/bin/env bash
# Configures a Nginx server so that /redirect_me is redirecting to another page
apt-get -y update
apt-get -y install nginx

echo 'Holberton School for the win!' > /usr/share/nginx/html/index.html

# stream editor. -i: to update the file
sudo sed -i '37i\ "\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" /etc/nginx/sites-enabled/default'

sudo service nginx start
