#!/usr/bin/env bash
# Configures a Nginx 404 page
apt-get -y update
apt-get -y install nginx

cd /var/www/html
echo 'Holberton School for the win!' > index.html

sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

sudo sed -i '/listen 80 default_server;/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;internal;}' /etc/nginx/sites-available/default

sudo service nginx restart