#!/usr/bin/env bash
# nginx must be running as nginx user
# and must be listening on all active IPs on port 8080

chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx nginx
sudo service nginx restart
