#!/usr/bin/env bash
# nginx must be running as nginx user and listening on port 8080 for all IPs
chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
